CONDUCTOR_PARAMETER_ENDPOINT = "tcp://*:44440"
CONDUCTOR_OUTPUT_ENDPOINT = "tcp://10.0.0.181:44441"
DEFAULT_ONSET_THRESHOLD = 5.0
DEFAULT_ONSET_PEAK_PICKING_WINDOW_SIZE = 2
DEFAULT_ONSET_PEAK_PICKING_WINDOW_TAIL = 2
ONSET_PREFIX = "onset"
SIZE_MULTIPLIER = 0.7
