# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ImpresarioSerialization

class FrequencyBand(object):
    all = 0
    subBass = 1
    bass = 2
    lowMidrange = 3
    midrange = 4
    upperMidrange = 5
    presence = 6
    brilliance = 7

