# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ImpresarioSerialization

class Identifier(object):
    onset = 0
    onsetProcessorParameters = 1
    pitch = 2
    pitchProcessorParameters = 3
    spectrogram = 4

