# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ImpresarioSerialization

class PitchMethod(object):
    schmitt = 0
    fcomb = 1
    mcomb = 2
    yin = 3
    yinfast = 4
    yinfft = 5

