Config:
  # absolute path to the raspberry pi image's boot directory
  boot_directory_path: ""

  # parameters for the raspberry pi's wpa supplicant
  network_country_code: ""
  network_ssid: ""
  network_password: ""

  # local ip of the raspberry pi
  pi_ip_address: ""

  # new password for root account on the raspberry pi
  pi_root_password: ""

  # ssh key for cloning github repos
  ssh_key_path: "secrets/ssh_key"

  # git credentials
  git_email: ""
  git_username: ""
